### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zcdliuwei** [YingqingHe/ScaleCrafter#1]
非常棒的工作，已经迫不及待想要试试了
请问，以SDXL v1.0 base为例，训练图像是1024^2大小，假设我要生成4096^2的图，耗时会比使用SDXL直接生成1024^2慢多少？
另外我正在搜集一批MJ的数据，然后使用SDXL v1.0 base做预训练模型进行微调，希望能达到MJ V5的效果，想请教两个问题：
1，您觉得这个微调SDXL来对齐midjourney的想法可行吗？
2，我只有一块A100，在大数据集上训练非常耗时，如果我先将搜集到的MJ数据缩小至256或者512，在该分辨率下训练，再使用您的方法生成1024甚至更高分辨率的图，您觉得可行吗
非常期待您的回复

**Comment by ssyang1999** [comment]
We test on A100 40G GPU, our method takes 600s to generate 4096x4096 images, which uses 35% more time than vanilla SD XL. 

It is plausible to fine-tune SD XL v1.0 base to approach MJ quality. Maybe try some parameter-efficient fine-tuning methods on 512x512 image data first?
