### ISSUE TITLE
Can we create custom image aspect ratios like 9:16 format? 

### ISSUE THREAD

**Issue by NeoAnthropocene** [YingqingHe/ScaleCrafter#14]
Hello, I noticed that the configs folder contains various aspect ratios such as 1:1 and 2:1. 

However, I'm looking for a 9:16 ratio suitable for Instagram stories. Could you provide an example for this particular ratio?

**Comment by ssyang1999** [comment]
Yes, you can create your custom image aspect ratios. If you wish to create 9:16 images, please select image width and height can be evenly divided by 64.  For example, you can use 768x1344 (9:15.75). It has a similar pixel number to 1024x1024, then you can modify a 1024x1024 config file by setting:
```yaml
latent_height = 168 # ${pixel_height} // 8 
latent_width = 96 # ${pixel_width} // 8
```

**Comment by NeoAnthropocene** [comment]
Excellent! Thank you @ssyang1999, that worked well for me.
Instead of 768x1344, I made it 1024x1792 (Since I have enough VRAM to render with a bigger size)

I'm putting here the config file and the samples for the other people who may encounter with this question.

./assets/dilate_settings/[sdxl_1792x1024.txt](https://github.com/YingqingHe/ScaleCrafter/files/12927433/sdxl_1792x1024.txt)
sdxl_1792x1024.yaml
```
ndcfg_tau: 0
dilate_tau: 30
inflate_tau: 0
sdedit_tau: 0
dilate_settings: ./assets/dilate_settings/sdxl_1792x1024.txt
inflate_settings: ~
ndcfg_dilate_settings: ~
inflate_transform: ~
progressive: false
num_inference_steps: 50
inference_batch_size: 1
num_iters_per_prompt: 1
latent_height: 224
latent_width: 128
pixel_height: 1792
pixel_width: 1024
```

And some Halloween eye-candies for you :)
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/3a2e5414-2132-456e-8363-ff7ca3acceb8)
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/4cb7ead8-0670-43be-ae49-83df4cc04374)
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/f385a25d-34f1-402a-a313-1c797723e554)
