### ISSUE TITLE
Question about settings for SDXL

### ISSUE THREAD

**Issue by deltheil** [YingqingHe/ScaleCrafter#16]
(Congrats on the great work!)

I was having a look at the [default example](https://github.com/YingqingHe/ScaleCrafter/blob/810363ab9843f91a5fdd19be3233e2e070fde3b3/README.md#stable-diffusion-xl-v10-base) (2048x2048 (4x) generation) for SDXL which uses [configs/sdxl_2048x2048.yaml](https://github.com/YingqingHe/ScaleCrafter/blob/810363ab9843f91a5fdd19be3233e2e070fde3b3/configs/sdxl_2048x2048.yaml) (= Table 10 in the paper) and these [dilate settings](https://github.com/YingqingHe/ScaleCrafter/blob/810363ab9843f91a5fdd19be3233e2e070fde3b3/assets/dilate_settings/sdxl_2048x2048.txt):

```txt
down_blocks.3.resnets.0.conv1:2
down_blocks.3.resnets.0.conv2:2
down_blocks.3.resnets.1.conv1:2
down_blocks.3.resnets.1.conv2:2
up_blocks.0.resnets.0.conv1:2
up_blocks.0.resnets.0.conv2:2
up_blocks.0.resnets.1.conv1:2
up_blocks.0.resnets.1.conv2:2
up_blocks.0.resnets.2.conv1:2
up_blocks.0.resnets.2.conv2:2
up_blocks.0.upsamplers.0.conv:2
mid_block.resnets.0.conv1:2
mid_block.resnets.0.conv2:2
mid_block.resnets.1.conv1:2
mid_block.resnets.1.conv2:2
```

I feel like there is an issue with the `down_blocks.3...` keys (aka `DB3` in the paper). Namely, it looks like an **off-by-one error**, i.e. **there are no such downblocks in the SDXL UNet** (at runtime, **these keys are just ignored** and the corresponding convolutions are not replaced by the `ReDilateConvProcessor`).

Instead the 3rd down-block corresponds to `down_blocks.2...` so these should be:

```txt
down_blocks.2.resnets.0.conv1:2
down_blocks.2.resnets.0.conv2:2
down_blocks.2.resnets.1.conv1:2
down_blocks.2.resnets.1.conv2:2
```

(Same applies to the other SDXL configs)

Looking forward to your feedback!

**Comment by ssyang1999** [comment]
Thanks for the comments. Yes, the dilate settings about `down_blocks.3` are ignored when running ScaleCrafter. We kept these settings to align the configuration in SD 2.1 and SD 1.5. We are trying to correct this ambiguity very soon.
