### ISSUE TITLE
Code for generating linear transforms of convolution dispersion

### ISSUE THREAD

**Issue by LeonHLJ** [YingqingHe/ScaleCrafter#29]
Thanks for your wonderful work. I couldn't locate the code responsible for producing linear transforms of convolution dispersion, only the adept transformation. Furthermore, I couldn't identify any instances where convolution dispersion is applied, suggesting that all judgment conditions against using the transform. Are there any intentions to publish the related code? Alternatively, could you offer some direction on how to access the code?

**Comment by ssyang1999** [comment]
Hi, we updated the code for solving dispersion transform. This is implemented with MATLAB. See https://github.com/YingqingHe/ScaleCrafter/tree/main/disperse

**Comment by ssyang1999** [comment]
We also updated our README.md for the usage of the codes. If you are interested in getting a custom dispersion transform, please check it as a guide.
