### ISSUE TITLE
Does this algorithm work with DDIM scheduler only?

### ISSUE THREAD

**Issue by eldercrow** [YingqingHe/ScaleCrafter#31]
I tried to generate images with DPM++ scheduler but got results with artifacts. I could not find any explanations about the scheduler in the paper and wondering what schedulers can be used with scalecrafter.

**Comment by YingqingHe** [comment]
Hi. We used the DDIM sampling schedule in our experiments. It is possible to try other schedules like the DPM++. Please feel free to adjust the hyperparameters related to the diffusion timesteps, including the `ndcfg_tau` and `dilate_tau`, which might have variable options for different sampling schedules.😊
