### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by andriyrizhiy** [YingqingHe/ScaleCrafter#6]
I'm testing your work. And I got bad results, maybe I did something wrong? Do you have the same results with these parameters?
Before testing, I set up an environment with your requirements

Example 1:
`python3 text2image.py --pretrained_model_name_or_path stabilityai/stable-diffusion-2-1-base \
--validation_prompt "A corgi sits on a beach chair on a beautiful beach, with palm trees behind, high details" \
--seed 23 \
--config ./configs/sd2.1_2048x2048.yaml \
--logging_dir ./out`
result: 
![1](https://github.com/YingqingHe/ScaleCrafter/assets/41432542/39b7859d-a922-48c1-890d-df727b19738b)
have repetition
Example 2:
`python3 text2image_xl.py \
--pretrained_model_name_or_path stabilityai/stable-diffusion-xl-base-1.0 \
--validation_prompt "A corgi sits on a beach chair on a beautiful beach, with palm trees behind, high details" \
--seed 23 \
--config ./configs/sdxl_4096x2048.yaml  \
--logging_dir ./out4`
![1](https://github.com/YingqingHe/ScaleCrafter/assets/41432542/ecc7b971-4635-49ac-8b86-2077bb0d3f12)
Blur and repetition
Example 3:
`python3 text2image.py --pretrained_model_name_or_path stabilityai/stable-diffusion-2-1-base \
--validation_prompt "A corgi sits on a beach chair on a beautiful beach, with palm trees behind, high details" \
--seed 23 \
--config ./configs/sd2.1_2048x1024.yaml \
--logging_dir ./out5`
![1](https://github.com/YingqingHe/ScaleCrafter/assets/41432542/7dc68118-8c0f-4430-a1e7-3d3666a834fd)
Have repetition

**Comment by hack-mans** [comment]
Similar experience but with SDXL 0.9, here's my first output:
`python text2image_xl.py --pretrained_model_name_or_path stabilityai/stable-diffusion-xl-base-0.9 --validation_prompt "portrait photo of a beautiful russian girl, with black pigtails, wearing fluffy coat, wide mid shot, derelict building, soft lighting, Hasselblad, Voigtländer 50mm lens, in style of Oleg Oprisco" --seed 323456789 --config ./configs/sdxl_4096x2048.yaml --logging_dir ./outputs`
![1](https://github.com/YingqingHe/ScaleCrafter/assets/119548070/ed9f909f-d4ee-4328-9aec-173b58f37f60)

**Comment by hack-mans** [comment]
2048x2048 is better but still a sort of smushy look to it
`python text2image_xl.py --pretrained_model_name_or_path stabilityai/stable-diffusion-xl-base-0.9 --validation_prompt "portrait photo of a beautiful russian girl, with black pigtails, wearing fluffy coat, wide mid shot, derelict building, soft lighting, Hasselblad, Voigtländer 50mm lens, in style of Oleg Oprisco" --seed 323456789 --config ./configs/sdxl_2048x2048.yaml --logging_dir ./outputs`
![1](https://github.com/YingqingHe/ScaleCrafter/assets/119548070/fe4bff76-c5e9-4ae5-9a5b-beb35635a14d)

**Comment by ssyang1999** [comment]
Hi. Thanks for your comments. We fixed some misconfigurations in sd2.1 2048x2048 and sdxl.  We are continually making ScaleCrafter better, please stay tuned. See the results below:

SD v2.1 2048x2048

![1](https://github.com/YingqingHe/ScaleCrafter/assets/70580297/eff2a307-e128-4cc4-a495-9b115e64e48f)

SD XL 1.0 2048x1024 
![1](https://github.com/YingqingHe/ScaleCrafter/assets/70580297/9ec68ac3-d55f-4793-bca8-b101949e3926)

![1)](https://github.com/YingqingHe/ScaleCrafter/assets/70580297/ee3cf052-55f0-4082-83b2-18be217699f4)
