### ISSUE TITLE
Lightning version support

### ISSUE THREAD

**Issue by IceClear** [YingqingHe/ScaleCrafter#7]
Hi. Great work.
May I know if the current repo supports [SD repo based on PyTorch lighting](https://github.com/Stability-AI/stablediffusion)?
It seems only diffusers-based repo is supported.
Thanks.

**Comment by vinthony** [comment]
you can check the lighting version here : https://github.com/YingqingHe/ScaleCrafter-ptl

**Comment by zwishenzug** [comment]
> you can check the lighting version here : https://github.com/YingqingHe/ScaleCrafter-ptl

Thanks for this, I was able to completely understand how it works from that very simple code and now begins the testing!

**Comment by IceClear** [comment]
Thanks for your kind reply!
