### ISSUE TITLE
How I should call my locally stored checkpoints in the script?

### ISSUE THREAD

**Issue by NeoAnthropocene** [YingqingHe/ScaleCrafter#8]
It throws an error when I'm trying to call a local model using the method below.

🤷‍♂️ Where am I making the mistake? How I should call my local checkpoints?

The script part for running the code:
```
python3 text2image_xl.py \
--pretrained_model_name_or_path ./models/juggernautXL_version5.safetensors \
--validation_prompt "a professional photograph of an astronaut riding a steel horse at Mars" \
--seed 23 \
--config ./configs/sdxl_2048x2048.yaml \
--logging_dir ./outputs
```

⚠ Output:
```
Traceback (most recent call last):
  File "text2image_xl.py", line 541, in <module>
    main()
  File "text2image_xl.py", line 405, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/astroboy/anaconda3/envs/scalecrafter/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1699, in from_pretrained
    raise ValueError(
ValueError: Calling CLIPTokenizer.from_pretrained() with the path to a single file or url is not supported for this tokenizer. Use a model identifier or the path to a directory instead.
```

Folder structure:
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/5b471209-fe56-45d0-94d3-f448fc9b31b3)

**Comment by hack-mans** [comment]
@NeoAnthropocene You might need to convert to Diffusers folder and pass that path rather than a safetensors checkpoint

**Comment by NeoAnthropocene** [comment]
> @NeoAnthropocene You might need to convert to Diffusers folder and pass that path rather than a safetensors checkpoint

Oh shoot! How did I miss that.
I found the diffusion model of [Juggernauth XL on Hugging Face](https://huggingface.co/stablediffusionapi/juggernaut-xl-v5) and then it worked.

The new code:
```
python3 text2image_xl.py \
--pretrained_model_name_or_path stablediffusionapi/juggernaut-xl-v5 \
--validation_prompt "a professional photograph of an astronaut riding a steel horse at Mars" \
--seed 23 \
--config ./configs/sdxl_2048x2048.yaml \
--logging_dir ./outputs
```

Results:
🖼️ with `sdxl_vanilla.yaml` config
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/b026c8be-5ed6-4781-8206-1e1c255f1a48)

🖼️ with `sdxl_2048x2048.yaml` config
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/07044651-e834-4d35-9c65-5d41d388378c)

**Comment by AlexanderKozhevin** [comment]
"home office room interior design, concept, hipster, photorealistic"
most of images are very sketchy
![download](https://github.com/YingqingHe/ScaleCrafter/assets/4464561/603a495f-8116-4350-8a5e-38e535887cda)

**Comment by NeoAnthropocene** [comment]
> "home office room interior design, concept, hipster, photorealistic" most of images are very sketchy ![download](https://user-images.githubusercontent.com/4464561/275196385-603a495f-8116-4350-8a5e-38e535887cda.jpeg)

Well I'm getting the same sketchy pictures as you with the prompt below, but I guess it is more capable with the one object. If you give more objects they came up not in detail.

Prompt:
`A knolling photo of Elite Ethan a renowned 35-50-year-old commercial photographer, in an upscale European studio setting,  is engrossed in his work. Surrounding him are his signature tools: a high-end DSLR, professional lenses, and studio lights. Central to the scene is a state-of-the-art portable power station, powering his equipment and highlighting its indispensable role in his workflow. Nearby, magazines featuring his work, collaboration notes, and a digital tablet displaying his portfolio attest to his industry stature. The ambiance subtly conveys the message: With reliable portable power, elevate your photography without constraints. Cinematic, ultra-realistic, hyper detail, cinematic lighting, magic neon, Canon EOS R3, nikon, f/1.4, ISO 200, 1/160s, 8K, in-frame, 8K`
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/4d95fc02-0f36-4350-a07c-a9875f50e95a)

Once you focused on one object here is the result as below.
(Unfortuınately I lost the prompt data because the code writes on the same files always. THis should be changed, I almost lost my whole previous renders)
![image](https://github.com/YingqingHe/ScaleCrafter/assets/112825147/5bc29402-2364-4a1f-bdeb-103e7cca9335)

**Comment by YingqingHe** [comment]
> THis should be changed, I almost lost my whole previous renders)

Hi, we have fixed this issue, check this: https://github.com/YingqingHe/ScaleCrafter/blob/21f9755a226b237f3761c2519084dcf36972798b/text2image_xl.py#L539  You could pull our update. Hope this could help~

**Comment by NeoAnthropocene** [comment]
> > THis should be changed, I almost lost my whole previous renders)
> 
> Hi, we have fixed this issue, check this:
> 
> https://github.com/YingqingHe/ScaleCrafter/blob/21f9755a226b237f3761c2519084dcf36972798b/text2image_xl.py#L539
> 
> You could pull our update. Hope this could help~

Thank you so much for the fast update 🙏
